title: "Cristian Porzio"
description: "Pensieri, storie e idee."

remote_theme: pages-themes/minimal

plugins:

- jekyll-remote-theme
- jekyll-paginate

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
future: true

# Pagination settings
paginate: 4
paginate_path: "/blog/page:num/"