title: "Cristian Porzio"
description: "Pensieri, storie e idee."

remote_theme: pages-themes/minimal

plugins:

- jekyll-remote-theme

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
future: true